# Generated by Django 4.0.1 on 2022-05-19 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0002_rename_article_articles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_number', models.BigIntegerField()),
                ('block_timestamp', models.DateTimeField()),
                ('block_hash', models.CharField(max_length=200)),
                ('transaction_hash', models.CharField(max_length=200)),
                ('transaction_index', models.IntegerField()),
                ('contract_type', models.CharField(max_length=200)),
                ('transaction_type', models.CharField(max_length=200)),
                ('token_address', models.CharField(max_length=200)),
                ('token_id', models.IntegerField()),
                ('from_address', models.CharField(max_length=200)),
                ('to_address', models.CharField(max_length=200)),
                ('amount', models.CharField(max_length=200)),
                ('verified', models.IntegerField()),
                ('operator', models.CharField(max_length=200)),
            ],
        ),
    ]
